on:
  push:
    branches: [ main ]  
name: 🚀 Deploy website on push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: rsync deployments
      uses: burnett01/rsync-deployments@7.0.1
      with:
        switches: -avzr --delete
        path: /
        remote_path: /home/u677671400/domains/clinico.site/public_html/api-clinico
        remote_host: clinico.site
        remote_port: 65002
        remote_user: u677671400
        remote_key: ${{ secrets.DEPLOY_KEY }}        
